### ISSUE TITLE
Lack of eslint-2 plugin and standards support

### ISSUE THREAD

**Issue by tierra** [codeclimate/codeclimate-eslint#100]
In the latest update to provide the `eslint-2` channel, I noticed that a few packages originally supported with ESLint 1.x are no longer provided in the ESLint 2.x channel:

In 1.x:
```
    "eslint-config-airbnb": "^5.0.0",
    "eslint-config-standard": "4.4.0",
    "eslint-plugin-babel": "2.1.1",
    "eslint-plugin-promise": "1.3.1",
    "eslint-plugin-react": "3.16.1",
    "eslint-plugin-standard": "1.3.1",
```

In 2.x:
```
    "eslint-config-airbnb": "^5.0.0",
    "eslint-plugin-babel": "2.1.1",
    "eslint-plugin-react": "3.16.1",
```

Three missing packages bother me in particular:

* `eslint-config-standard` (removed)
* `eslint-config-standard-react` (never provided, but react plugin is?)
* `eslint-plugin-promise` (removed)

Is there any possibility of addressing all three? I'm really starting to consider writing a custom CodeClimate engine because I've had absolutely no stats in CodeClimate for my project for over a couple months now, and the new `eslint-2` channel still hasn't solved it.

**Comment by tierra** [comment]
I'm still pretty baffled as to why the engine doesn't just use the project's package dependency, along with possibly some globally installed deps necessary for the engine itself, and why it's necessary to even use a forked (and manually maintained) copy of the ESLint code itself. Can anyone explain the reason for either of these decisions that have made maintaining or using this engine so difficult?

**Comment by dblandin** [comment]
Hey @tierra,

We actually do vendor in many of the plugins you mention. You can see the [current list of vendored plugins and configs](https://github.com/codeclimate/codeclimate-eslint/blob/pb-eslint-2/package.json#L13-L20) used in the eslint-2 channel. The eslint-2 channel is built from the [branch](https://github.com/codeclimate/codeclimate-eslint/tree/pb-eslint-2) tracked in #92. You may have stumbled upon the [eslint-2 branch](https://github.com/codeclimate/codeclimate-eslint/tree/eslint-2) in this repo which is outdated and does not represent the eslint-2 channel.


> I'm still pretty baffled as to why the engine doesn't just use the project's package dependency, along with possibly some globally installed deps necessary for the engine itself.

I've discussed this recently in other comments, so I'll refer you to those: https://github.com/codeclimate/codeclimate-eslint/issues/86#issuecomment-222712720, https://github.com/codeclimate/codeclimate-eslint/issues/86#issuecomment-222721974, https://github.com/codeclimate/codeclimate-eslint/issues/80#issuecomment-223386512

The gist is: Our system isn't yet ready to execute user-provided code. We do plan to let users install project dependencies during analysis, but we're not quite there yet.

Given this limitation, we're usually pretty accommodating towards requests to vendor additional plugins or configs as long as it would benefit the greater Code Climate community, which in the case of popular packages is often the case.

> and why it's necessary to even use a forked (and manually maintained) copy of the ESLint code itself

Thanks to the work in #79, we no longer use a forked copy of ESLint for the eslint-2 channel, as you can see [here](https://github.com/codeclimate/codeclimate-eslint/blob/pb-eslint-2/package.json#L12).

**Comment by tierra** [comment]
Thanks for the clarification, and sorry about the confusion with the old eslint-2 branch.

Is there any chance of including the `eslint-config-standard-react` package then?

**Comment by dblandin** [comment]
@tierra Sure, sounds good to me. I'll open up a PR adding that package.

**Comment by dblandin** [comment]
Hey @tierra,

I just pushed out a new engine image to the eslint-2 channel with support for the [eslint-config-standard-react] and [eslint-config-standard-jsx] configs.

Let me know if it works for you!

[eslint-config-standard-react]: https://github.com/feross/eslint-config-standard-react
[eslint-config-standard-jsx]: https://github.com/feross/eslint-config-standard-jsx

**Comment by tierra** [comment]
Just tested that out, and it's working great now, thanks!
