### ISSUE TITLE
Add support for hapijs eslint plugin

### ISSUE THREAD

**Issue by idoshamun** [codeclimate/codeclimate-eslint#103]
I know that you are currently don't support NPM eslint plugins but only a few popular plugins.
If possible please add support for the hapijs eslint plugin.
[https://www.npmjs.com/package/eslint-plugin-hapi](https://www.npmjs.com/package/eslint-plugin-hapi)

**Comment by pbrisbin** [comment]
Hi @idoshamun sorry for the delayed response here.

I think it'd be OK to add that plugin. We usually look at download count on npm to try and gauge popularity as a rough metric for what we should bundle into the engine. If you'd be able to open the PR to add it, that'd certainly speed things up. #118 is a recent example of such a PR.

**Comment by idoshamun** [comment]
I'll do my best! need to make some time for it

**Comment by idoshamun** [comment]
I've opened a new PR #124

**Comment by pbrisbin** [comment]
Thanks. I'm going to close this and we'll pick things up in the PR.
