### ISSUE TITLE
Definition for rule 'flowtype/define-flow-type' was not found

### ISSUE THREAD

**Issue by jdelStrother** [codeclimate/codeclimate-eslint#113]
According to https://github.com/codeclimate/codeclimate-eslint/pull/106 the flowtype plugins ought to be installed, but I'm still seeing errors on, eg, https://codeclimate.com/repos/5541ec0c69568016db0009ad/pull/1186.

**Comment by bjrnt** [comment]
Experiencing the same issue for https://codeclimate.com/repos/56e0de913ce41f027f002107/pull/274. I'm talking to support now about how to solve it. I'll post an update here if it gets resolved. :)

**Comment by bjrnt** [comment]
Seems like this was fixed in #121! :)

**Comment by pbrisbin** [comment]
Thanks @bjrnt, I'm going to go ahead and close. Feel free to re-open if you're still having trouble. If you do, please note that we can't view those links to your private projects (not without granting us permission via support), so if you could include relevant data like your `.codeclimate.yml`, other configs, and the output you're seeing, that'd be great.
