### ISSUE TITLE
eslint-3 channel

### ISSUE THREAD

**Issue by gpbl** [codeclimate/codeclimate-eslint#125]
Hi! Any news about supporting eslint v3 and related upgraded plugins? 

This is what we are using in development right now:

```
    "eslint": "3.3.1",
    "eslint-config-airbnb": "10.0.1",
    "eslint-plugin-import": "1.13.0",
    "eslint-plugin-jsx-a11y": "2.1.0",
    "eslint-plugin-react": "6.1.2",
```

Thanks 👍

**Comment by jeffijoe** [comment]
Same, need eslint 3 pretty badly.

**Comment by pbrisbin** [comment]
Thanks for the nudge. This is definitely on our list of things to do, but we're a small team and can't offer a specific timeline at the moment. Sorry for the delay.

**Comment by rwwagner90** [comment]
Any progress on this?

**Comment by abey-alex** [comment]
+1

**Comment by dblandin** [comment]
Hey everyone!

I'm happy to announce that we just released an `eslint-3` channel which is now available via the [CLI][] and [codeclimate.com][].

[codeclimate.com]: https://codeclimate.com
[CLI]: https://github.com/codeclimate/codeclimate

As with the `eslint-2` channel, you can opt-in to the `eslint-3` channel by updating your `.codeclimate.yml` file:

```yaml
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
```

You can check out the current version of vendored plugins for the `eslint-3` channel, [via its package.json](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-3/package.json).

We're planning to update [our](https://docs.codeclimate.com/docs/eslint) [docs](https://docs.codeclimate.com/docs/engine-channels) and provide channel-specific contributing instructions in the README soon, but in the meantime, here's a quick contributing note:

The `master` branch of this repo maps to the `stable` channel (currently targeting ESLint 1), which is used by default. Alternate channels can be found in this repo's [branch listing](https://github.com/codeclimate/codeclimate-eslint/branches). Any branch with the `channel/` prefix maps directly to a channel.

When opening up PRs for this engine, you should set the base to the branch that maps to the appropriate channel:

```
ESLint 1 (stable channel) -> master
ESLint 2 (eslint-2 channel) -> channel/eslint-2
ESLint 3 (eslint-3 channel) -> channel/eslint-3
```
