### ISSUE TITLE
Syntax validation

### ISSUE THREAD

**Issue by gilbarbara** [codeclimate/codeclimate-eslint#150]
Hello,

I'm getting this error while running in the .com engine.
```
Configuration for rule "comma-dangle" is invalid:
	Value "[object Object]" must be an enum value.
```

My `comma-dangle` rule:
```
"comma-dangle": ["warn", {
  "arrays": "always-multiline",
  "objects": "always-multiline",
  "functions": "only-multiline"
}],
```

Probably a ESLint version issue? I couldn't find which version the engine was running on.
Upgrade time? :)

**Comment by wfleming** [comment]
HI @gilbarbara,

The eslint 3 version of our engine was on `3.6.1`, and it looks like this format was added more recently than that. I just released an update to bring it up to `3.9.1`, which should fix your issue.

Also, if your `.codeclimate.yml` does not specify a `channel` for ESLint, please update it to specify `channel: eslint-3` (see example below). For legacy reasons, configurations that don't specify `channel` still get ESLint 1.

```
eslint:
  enabled: true
  channel: eslint-3
```

**Comment by gilbarbara** [comment]
Hello @wfleming 
Cool, I suspect that.
The error ocurred in a repo that already uses the proper [channel](https://github.com/gilbarbara/codeclimate-stylelint/blob/master/.codeclimate.yml).

Thanks

**Comment by wfleming** [comment]
Cool, I wasn't sure from the initial issue if the repo in question had the `channel` set.

I'm going to close this now, but let us know if you're still seeing the same error on new builds.
