### ISSUE TITLE
Allow versions for sharable configs

### ISSUE THREAD

**Issue by mike-schultz** [codeclimate/codeclimate-eslint#152]
It would be great to have a way to target specific versions of sharable configs from the `.codeclimate.yml` or some other mechanism. 

**Use case:** I'm using the hosted version of codeclimate and channel-3 of eslint. My config extends google and I've updated to their newest version (v0.7.0) but it looks like the engine's dependencies haven't been updated yet (on v0.6.0 it looks like). 

Google's newest update is actually pretty significant in terms of lint checks such as requiring dangling commas in objects. That in itself throws hundreds of warnings for my codebase. Simply updating the engine with the newest build would solve my issue, but probably confuse all other google-sharable-config users on codeclimate. Thus, it would be great if we could target our own dependencies at a config level!

**Comment by maxjacobson** [comment]
Hi @mike-schultz, thanks for letting us know about that update.

I think pushing forward with the update is worth doing! Feel free to make a PR against our `channel/eslint-3` branch which updates the package and we'll be happy to ship it. Otherwise we'll plan to do it as soon as we can.

**Comment by mike-schultz** [comment]
Thanks for the reply @maxjacobson! I went ahead and did that PR for eslint-config-google.

**Comment by maxjacobson** [comment]
Thanks, going to close this since we have that PR now.
