### ISSUE TITLE
Add support for eslint-plugin-meteor

### ISSUE THREAD

**Issue by athyuttamre** [codeclimate/codeclimate-eslint#155]
Meteor is a popular JavaScript framework and [`eslint-plugin-meteor`](https://www.npmjs.com/package/eslint-plugin-meteor) is often used and recommended by the [official guide](https://guide.meteor.com/code-style.html#eslint-installing).

Could you add support for this please?

**Comment by maxjacobson** [comment]
Done! Thanks for your patience. Make sure you're using the eslint-3 channel (https://docs.codeclimate.com/docs/eslint#section-eslint-versions)

**Comment by athyuttamre** [comment]
Thank you so much for this!
