### ISSUE TITLE
support for `eslint-plugin-immutable`, `eslint-plugin-import-order`, `eslint-plugin-jasmine`

### ISSUE THREAD

**Issue by bobjflong** [codeclimate/codeclimate-eslint#164]
Hi,

We would like to use the `eslint-3` channel but it is missing these plugins. Could they be added?

Thanks

**Comment by maxjacobson** [comment]
@bobjflong sure thing. Made a PR: #165 and will plan to ship it later today.

Our process for adding plugins is written out here btw if you ever want to make a PR: https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-3/CONTRIBUTING.md

**Comment by bobjflong** [comment]
thanks!
