### ISSUE TITLE
Add Support for eslint-plugin-inferno

### ISSUE THREAD

**Issue by derekhubbard** [codeclimate/codeclimate-eslint#179]
We are using Inferno and the eslint inferno plugin, but this isn't currently supported by the CodeClimate eslint-3 channel. 

Here is the error we receive when using the plugin: 
```
File `.eslintignore` ignored because of your .eslintignore file.
File `.nvmrc` ignored because of your .eslintignore file.
File `.eslintrc.js` ignored because of your .eslintignore file.
File `client/.gitignore` ignored because of your .eslintignore file.
File `.eslintrc` ignored because of your .eslintignore file.
File `.gitignore` ignored because of your .eslintignore file.
File `.codeclimate.yml` ignored because of your .eslintignore file.
File `.csslintrc` ignored because of your .eslintignore file.
/usr/src/app/node_modules/eslint/lib/config/plugins.js:137
                throw err;
                ^

Error: Failed to load plugin inferno: Cannot find module 'eslint-plugin-inferno'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/usr/src/app/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/usr/src/app/node_modules/eslint/lib/config/plugins.js:151:21)
    at Object.load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:504:21)
    at loadConfig (/usr/src/app/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/usr/src/app/node_modules/eslint/lib/config.js:130:29)
```

Can `eslint-plugin-inferno` be added as a codeclimate eslint-3 supported plugin?

**Comment by derekhubbard** [comment]
As a temporary workaround for this, I'm trying to point the CodeClimate ESLint engine (eslint-3) to use a different `.estlintrc.js` configuration file which does not pull in and configure any rules using the Inferno plugin. But it seems like ESLint is still trying to load the Inferno plugin and can't find it. 

Any other suggestions for how to work around this for the time being?

**Comment by maxjacobson** [comment]
@derekhubbard Hi Derek! Thanks for opening this issue. We've just [fixed a bug](https://github.com/codeclimate/codeclimate-eslint/pull/182) related to specifying an alternate config file, so if you'd like to try that again, will you let us know if that works.

If you'd like to make a PR adding this plugin, please feel free. See [CONTRIBUTING.md](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-3/CONTRIBUTING.md)

**Comment by derekhubbard** [comment]
@maxjacobson Excellent - thanks! I will try out the "alternate config file" approach again and see if I have better luck. 

I'd be glad to submit a PR to add the inferno plugin - thanks for pointing me in the right direction!

**Comment by derekhubbard** [comment]
#185

**Comment by maxjacobson** [comment]
@derekhubbard Ah, yep. I believe that should be resolved since https://github.com/codeclimate/codeclimate-eslint/pull/189 was merged

**Comment by dblandin** [comment]
Just pushed an update including #185 out. Should now be available via codeclimate.com or the CLI.

Thanks!
