### ISSUE TITLE
Add support for eslint-import-resolver-meteor

### ISSUE THREAD

**Issue by athyuttamre** [codeclimate/codeclimate-eslint#200]
Support for Meteor was recently added to the eslint engine, but I forgot to mention another key component. Meteor projects often import like this:

- `import { Meteor } from 'meteor'`
- `import /imports/ui/components/button/button`

Typically the eslint engine fails both with the error `Resolve error: unable to load resolver "meteor".`. The fix is to use the [`eslint-import-resolver-meteor`](https://www.npmjs.com/package/eslint-import-resolver-meteor) plugin, which is also recommended by Meteor's official guide.

Could we add support for this please?

**Comment by athyuttamre** [comment]
I suppose this is similar to https://github.com/codeclimate/codeclimate-eslint/issues/143. Looks like the change from that issue was reverted, and support was never added again. Any chance of this working?

**Comment by dblandin** [comment]
@athyuttamre Yep. Unfortunately adding support for the `eslint-import-resolver-meteor` plugin would hit the same limitations as #143. We've talked internally of blacklisting rules that rely on npm module resolution within the engine until we have a better solution.

**Comment by gfink57** [comment]
We have the same requirement for handling Meteor imports as @athyuttamre.  On the order of 6K associated errors in our analysis runs.

**Comment by dblandin** [comment]
Blacklisting rules that rely on npm module resolution is in the works. I'll comment again when I have an update. Thanks for your patience!

In the meantime, if the invalid issues are coming from the same checks you can disable the checks entirely by excluding them within your `.codeclimate.yml` file:

https://docs.codeclimate.com/v1.0/docs/disabling-individual-checks

**Comment by dblandin** [comment]
I've opened up [a new issue](https://github.com/codeclimate/codeclimate-eslint/issues/222) which will track work to ignore rules relying on npm module resolution. I'm going to go ahead and close this issue as we won't be able to support such rules at this time

Thanks!
