### ISSUE TITLE
Does the eslint engine support customized parser?

### ISSUE THREAD

**Issue by xinthink** [codeclimate/codeclimate-eslint#21]
Hi,
I'm using the [babel-eslint](https://github.com/babel/babel-eslint) as parser, but the engine complains `Cannot find module 'babel-eslint'`

.eslintrc:
```js
{
  "parser": "babel-eslint",          // https://github.com/babel/babel-eslint
  "plugins": [
    "react"                          // https://github.com/yannickcr/eslint-plugin-react
  ],
  "env": {
    "es6": true,
    "node": true
  },
  "ecmaFeatures": {
    "modules": true,
    "jsx": true
...
```

my .codeclimate.yml
```yml
engines:
  eslint:
    enabled: true
```

**Comment by GordonDiggs** [comment]
Hi there! We, unfortunately, are unable to support parsers and plugins right now. It is in our roadmap to support them. Follow #10 for updates when we release the ability to do so
