### ISSUE TITLE
Update eslint to the latest version

### ISSUE THREAD

**Issue by JCMais** [codeclimate/codeclimate-eslint#23]
The code currently breaks if someone is using new options from eslint.

**Comment by ABaldwinHunter** [comment]
@JCMais Thanks for your feedback! We're working to make updates to our `eslint` engines to support additional features.

**Comment by gilbarbara** [comment]
:+1:

**Comment by jrencz** [comment]
:+1:
It seems to me that you're using 1.2
I'm experiencing problems with http://eslint.org/docs/rules/indent.html#options validation

**Comment by dblandin** [comment]
Hey everyone!

We've updated our fork with the `v1.5.1` release of ESLint and just pushed the updated engine to our docker registry. All of the new configuration options are supported. The new engine is now live through the engine platform. Thanks for your patience!

**Comment by JCMais** [comment]
@dblandin when should I expect it to hit http://codeclimate.com/, or it's already updated there too?

**Comment by dblandin** [comment]
@JCMais Any analysis for a repo configured to use the new engine platform will pull down the updated ESLint engine. Both the hosted service on https://codeclimate.com and the Code Climate CLI pull from the same docker registry. :+1:
