### ISSUE TITLE
Looks like eslint parsers aren't supported

### ISSUE THREAD

**Issue by sivakumar-kailasam** [codeclimate/codeclimate-eslint#28]
I use the [babel-eslint](https://www.npmjs.com/package/babel-eslint) parser in my project and it seems the engine doesn't seem to support this.

//cc @mrb

**Comment by mikz** [comment]
The same problem here. Can it be added to `package.json` ?

**Comment by jcreamer898** [comment]
Yup, seems to be an issue here too... 

![](http://d.pr/i/1a0ty+)

**Comment by rodneyrehm** [comment]
same issue here.

**Comment by bastien** [comment]
:+1:

**Comment by nmqanh** [comment]
:+1:

**Comment by GordonDiggs** [comment]
Hey all! We are now bundling `babel-eslint` with the engine, so you should be able to use it correctly!
