### ISSUE TITLE
Support for ESLint 4.0.0

### ISSUE THREAD

**Issue by kunagpal** [codeclimate/codeclimate-eslint#283]

**Comment by msteward** [comment]
ESLint v4+ supports the eslintignore being inside the package.json file too so this might need a tweak to the init scripts to not create an eslintrc file by default?

**Comment by kunagpal** [comment]
@msteward http://eslint.org/docs/user-guide/migrating-to-4.0.0 doesn't suggest that `.eslintignore` files are deprecated. Since most people would prefer to keep their `package.json` files bloat free, an alternative course of action here could be to keep the init scripts as is, and ensure that the `channel: eslint-4` branch on this repository respects the ignore config within `packge.json` (Although that is something that ESLint v4.x would handle anyway).

**Comment by kunagpal** [comment]
@chrishulton Is there an E.T.A on this?

**Comment by chrishulton** [comment]
Hey @kunagpal, sorry I missed this issue.  Supporting eslint 4 sounds worthwhile, but due to other priorities, we aren't working on it at this time.  If we do begin work on this, we'll provide an update here with an ETA.

**Comment by benmccann** [comment]
I would really love to see this. I want to specify `ignoreEOLComments` in my `.eslintrc` file, but it looks to me like I can only set that option since ESLint v4.

**Comment by kunagpal** [comment]
This is now available via the `eslint-4` channel, thanks! 👍

**Comment by pointlessone** [comment]
A bit premature celebration. It's about to be available, but not just yet.

**Comment by benmccann** [comment]
Yeah, I get `Unable to find an image for eslint:eslint-4. Available channels: ["stable", "eslint-1", "eslint-2", "eslint-3"].`

Would you be able to report back here when it's available?

**Comment by pointlessone** [comment]
Sure.

**Comment by kunagpal** [comment]
@pointlessone Is the ESLint 4 channel available now?

**Comment by pointlessone** [comment]
Yes, but CLI has not been updated yet. You may need manually install the engine. Also note, that you will need to make sure your ESLint config is compatible with v4. Auto upgradng is not supported yet.

**Comment by pointlessone** [comment]
`eslint-4` channel is available both on CC and in CLI.

**Comment by WesTyler** [comment]
Is the intention to bring the main module up to eslint 4 soon? Just curious.
