### ISSUE TITLE
eslint-plugin-flowtype: Rule flowtype/no-types-missing-file-annotation not found

### ISSUE THREAD

**Issue by majagrubic** [codeclimate/codeclimate-eslint#285]
I've recently added `eslint-plugin-flowtype` as a dependency to my project. According to  [docs]( https://docs.codeclimate.com/v1.0/docs/eslint#section-supported-plugins), this plugins is supported in `eslint-3` channel, which I'm using. Locally, grunt eslint task completes without errors.  Same task in CodeClimate was, however, giving me an error: `flowtype/no-types-missing-file-annotation` rule could not be found. I switched that specific rule off for now, and all other rules seem to be working fine. 
Is there a known issue with this rule? Can you integrate it with CodeClimate eslint?

**Comment by ale7714** [comment]
@majagrubic hi, thank you for reporting this issue. I'm looking into it and will let you know when we have a resolution.

**Comment by ale7714** [comment]
@majagrubic today we updated `codeclimate-eslint` to include support for `flowtype/no-types-missing-file-annotation` rule. You should be able to turn on the rule again. I'll be closing the issue for now. Feel free to re-open it if you find anything.
