### ISSUE TITLE
Support for Lerna

### ISSUE THREAD

**Issue by FezVrasta** [codeclimate/codeclimate-eslint#288]
I recently moved my repository to [Lerna](https://github.com/lerna/lerna), using it, I decided to create a package to share my ESLint configuration across my other packages.

Locally, everything works properly, because when I install the package.json dependencies, a `postinstall` hook runs `lerna bootstrap`, which takes care to link my `eslint-config-popper` package inside the `node_modules` of all my others.

But when Code Climate tries to lint my project, it can't find my `eslint-config-popper` and crashes.

I see 2 problems with the current situation:

1. Seems like the linting step of Code Climate doesn't install the `eslint-*` dependencies to make ESLint use them later, but only supports a small set of "certified" packages.
2. Code Climate doesn't support monorepos (managed by Lerna), so it will never know that I have multiple packages in the same repository

If it helps, this is the PR where I added Lerna:
https://github.com/FezVrasta/popper.js/pull/314

This is a sample .babelrc.js:
https://github.com/FezVrasta/popper.js/pull/314/files#diff-da5604fca9fbb9419c26963ae4e32a07

This is my eslint-config-popper:
https://github.com/FezVrasta/popper.js/pull/314/files#diff-129e262bf44c2d16b27ebc7c87c047a1

**Comment by filipesperandio** [comment]
Closing as this is old, probably not relevant any more.

For context, CodeClimate plugins don't have network access, so the required plugins have to be installed in the engine itself and configuration files already present.

There is a `prepare` step that does have access to network and helps with shared configs, you can see how to configure it here: https://docs.codeclimate.com/docs/configuring-the-prepare-step
