### ISSUE TITLE
[Suggestion] Automate GreenKeeper pull request management

### ISSUE THREAD

**Issue by kunagpal** [codeclimate/codeclimate-eslint#292]
Reference: https://github.com/greenkeeper-keeper/reference-instance

**Comment by maxjacobson** [comment]
Hi Kunal 👋. Thanks for sharing. That seems cool. I think we'll prefer to manually merge PRs. We like robots, but also like to do some QA with each release, so we shouldn't merge until we're prepared to QA and release an updated engine on codeclimate.com.
