### ISSUE TITLE
Upgrade `eslint-plugin-import` to 2.7.x

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-eslint#318]
Customer request to upgrade `eslint-plugin-import`.

He mentioned:
> We need to have the latest version of eslint-plugin-import (https://www.npmjs.com/package/eslint-plugin-import), which is currently v2.7.x since there is a added feature we need for our monorepo configuration.

and 

> The feature we need is support to specify the package.json for the no-extraneous-dependencies rule. The PR for that feature can be found here: https://github.com/benmosher/eslint-plugin-import/pull/685. It was released in the v2.7.0 version. The issue itself is thoroughly documented here: https://github.com/benmosher/eslint-plugin-import/issues/458.

----

Looks like we're currently using [2.2.0](https://github.com/codeclimate/codeclimate-eslint/blob/master/package.json#L42)

**Comment by dblandin** [comment]
@efueger Do you know which channel of this engine the customer is using?

stable is currently tracking eslint v3

**Comment by GordonDiggs** [comment]
Closing for now - we've updated a bunch of plugins recently. Let me know if this comes back up!
