### ISSUE TITLE
ESLint plugin disparity across master and channel/eslint-4

### ISSUE THREAD

**Issue by kunagpal** [codeclimate/codeclimate-eslint#319]
Master: https://github.com/codeclimate/codeclimate-eslint/blob/master/package.json#L10

ESLint4: https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json#L11

**Comment by GordonDiggs** [comment]
Hey @kunagpal this is due largely to the fact that several plugins do not yet support ESLint 4. Are there any that you know of that have released support that are missing?

**Comment by kunagpal** [comment]
Well, I've personally used the following:
1. eslint-plugin-jsdoc
2. eslint-plugin-lodash
3. eslint-plugin-mocha
4. eslint-plugin-mongodb
5. eslint-plugin-security

I'll update the list with time.

**Comment by kunagpal** [comment]
The following plugins are either in progress, do not support, or are unknown:
1. eslint-plugin-angular
1. eslint-plugin-babel
1. eslint-plugin-ejs
1. eslint-plugin-ember
1. eslint-plugin-ember-suave
1. eslint-plugin-filenames
1. eslint-plugin-flowtype
1. eslint-plugin-hapi
1. eslint-plugin-immutable
1. eslint-plugin-import-order
1. eslint-plugin-inferno
1. eslint-plugin-jasmine
1. eslint-plugin-jest
1. eslint-plugin-jquery
1. eslint-plugin-json
1. eslint-plugin-jsx-a11y
1. eslint-plugin-lodash-fp
1. eslint-plugin-meteor
1. eslint-plugin-promise
1. eslint-plugin-react-intl
1. eslint-plugin-react-native
1. eslint-plugin-standard
1. eslint-plugin-vue
1. eslint-plugin-xogroup

**Comment by kunagpal** [comment]
@GordonDiggs Ping.

**Comment by dblandin** [comment]
@kunagpal I'd gladly look at a PR if you have time to open one.
