### ISSUE TITLE
ESLint 4: Add eslint-plugin-flowtype package back?

### ISSUE THREAD

**Issue by rye** [codeclimate/codeclimate-eslint#336]
From #331 and #319, it feels like the reason that most of those plugins were removed was that they don't have declared support for ESLint 4.

I'd love to hear from someone who has had difficulties using `eslint-plugin-flowtype` with ESLint 4 in production.  As it stands, moving from `master` to `channel/eslint-4` on CodeClimate was a regression for my team as we lost access to this flowtype plugin—we now get repetitive errors about undefined defs.  I have a branch, [rye:eslint-4--add-eslint-plugin-flowtype-back](https://github.com/rye/codeclimate-eslint/tree/eslint-4--add-eslint-plugin-flowtype-back), which adds v2.35.1 to the `package.json` file.

Please do let me know if there is a workaround or if I'm off-base on this.

**Comment by wfleming** [comment]
Hi @rye,

Can you go ahead and open a PR from your branch here? We did remove plugins that didn't seem to be compatible with ESLint 4, but if they have been updated since then to be compatbile (or we were incorrect to remove them in the first place), we'd be happy to add them back!

**Comment by rye** [comment]
@wfleming, expect a PR shortly.  I don't know if there is _declared_ support for ESLint in this plug-in, but their version specs do not explicitly disallow ESLint 4. (and, indeed, people have been using `eslint-plugin-flowtype ` with ESLint 4 with good results)
