### ISSUE TITLE
jsx-multiline eslint-config-airbnb

### ISSUE THREAD

**Issue by chrisjbrown** [codeclimate/codeclimate-eslint#353]
code climate build error
```javascript
/usr/src/app/lib/validate_config.js:17
        throw e;
        ^

Error: /usr/local/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-wrap-multilines" is invalid:
	Value "data["0"].arrow" has additional properties.
```
codeclimate.yml
```javascript
  eslint:
    enabled: true
    channel: "eslint-3"
```

eslintrc
```javascript
  "extends": [
    "react-app",
    "eslint-config-airbnb"
  ],
```

**Comment by toddmazierski** [comment]
Hi, @chrisjbrown! Sorry for the very delayed response.

I'm having trouble reproducing the error message you're seeing—are you still able to? If yes, do you mind providing a few additional details?

Is this project you're working on open-source? I'd like to inspect the `.codeclimate.yml` and `.eslint` files in full. Also, are you seeing this error on the web site or with the CLI?

Thanks!

**Comment by chrisjbrown** [comment]
I've been helped by code climate support with this. Still experiencing some issues but they are better described in this issue now.

https://github.com/codeclimate/codeclimate-eslint/issues/361
