### ISSUE TITLE
Consider bumping eslint-plugin-vue version

### ISSUE THREAD

**Issue by filipalacerda** [codeclimate/codeclimate-eslint#365]
# Bug Template

## Actual Behavior
With the current `eslint-plugin-vue` bundled in codeclimate-eslint, when adding the newest version for `eslint-plugin-vue` - https://github.com/vuejs/eslint-plugin-vue/releases/tag/v4.2.0, codeclimate job fails although the linter succeeds when running by itself (without codeclimate)

## Expected Behavior
Should be able to use any version of `eslint-plugin-vue`

## Steps to reproduce
Add `eslint-plugin-vue` to a project using any version after `4.0.0`
Here's the job output: https://gitlab.com/gitlab-org/gitlab-ee/-/jobs/47298828

> 1. _Include configurations used in your: <br>
> (1) .codeclimate.yml <br>
```
eslint:
    enabled: true
```
> (2) config files for the oss analysis tool._<br>

Link to the .eslintrc file: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.eslintrc

> 2. _If possible, use our CLI with [the debug option](https://github.com/codeclimate/codeclimate#environment-variables) to provide additional info, including any stderr produced by the engine._ `CODECLIMATE_DEBUG=1 codeclimate analyze -e eslint`

## Relevant links
I see 2 open MRs to fix this in this repo, but I don't see any activity in any of them:
- https://github.com/codeclimate/codeclimate-eslint/pull/358
- https://github.com/codeclimate/codeclimate-eslint/pull/364

I didn't know in which one to ask, I thought an issue would be more helpful!

We had to disable eslint in codeclimate in order to be able to use this plugin: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.codeclimate.yml#L16

Please let me know if there's something I can do to help! Thanks!

**Comment by larkinscott** [comment]
Hi @filipalacerda! Sorry for the delay on this. Bumping it now.

**Comment by blackjid** [comment]
Hi @larkinscott thanks for the update!

would it be possible to rebuild the `codeclimate/eslint:eslint-4` image with the latest updates?? Right know the vue plugin is not available on the v4 channel.

Thanks!

**Comment by Loremaster** [comment]
Are there any updates on that? We really want to `eslint-plugin-vue` (4.2.2) with `eslint-4` channel.

**Comment by filipalacerda** [comment]
This was already merged, it's already possible to use eslint 4.0.0

We were able to successfuly use eslint plugin vue with codeclimate 🎉 

I'll go ahead and close this issue :)

**Comment by larkinscott** [comment]
Hey @blackjid! Sorry for the delay on this. I'll go ahead and see if we can update the ```eslint-4``` channel with this plugin and get right back to you.

**Comment by Loremaster** [comment]
Thank you @larkinscott! Hope it can be done soon!

**Comment by larkinscott** [comment]
Hey @Loremaster! Sorry for the delay on my end, but thanks for the PR! I'm going to merge it now.
