### ISSUE TITLE
ESLint-4 prettier support.

### ISSUE THREAD

**Issue by aichholzer** [codeclimate/codeclimate-eslint#383]
## Actual Behavior

My `.codeclimate.yml` file:
```js
version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
exclude_patterns:
  - "**.json"
  - "**.md"
  - "**.yml"
```

when trying to run codeclimate's analysis it fails:

```js
/usr/src/app/lib/validate_config.js:18
        throw e;
        ^

TypeError: Cannot read property 'recommended' of undefined
Referenced from: /code/.eslintrc.json
    at loadConfigFile (/usr/local/node_modules/eslint/lib/config/config-file.js:211:40)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:486:18)
    at load (/usr/local/node_modules/eslint/lib/config/config-file.js:550:20)
    at configExtends.reduceRight.e (/usr/local/node_modules/eslint/lib/config/config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (/usr/local/node_modules/eslint/lib/config/config-file.js:403:28)
    at loadFromDisk (/usr/local/node_modules/eslint/lib/config/config-file.js:514:22)
    at Object.load (/usr/local/node_modules/eslint/lib/config/config-file.js:550:20)
    at Config.getLocalConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/usr/local/node_modules/eslint/lib/config.js:180:43)
```

[This](https://codeclimate.com/github/CometaFront/Cometa/builds/1) is the failing build.

## Expected Behavior

It should run normally and pass, since according to [this](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json), you do support `eslint-config-prettier`, `eslint-plugin-prettier` and `prettier` in your ESLint-4 channel

## Steps to reproduce

This is happening on the `master` branch, therefore, please feel free to fork it. Perhaps you want to take a look at the `package.json` file.

**Comment by aichholzer** [comment]
@toddmazierski -I also tried the `eslint-3` channel and [the issue](https://codeclimate.com/github/CometaFront/Cometa/builds/17) is the same.

**Comment by toddmazierski** [comment]
Hi, @aichholzer! Sorry for the delay in getting back to you. I think there might be a syntax error in your `.eslintrc`. Mind trying the following change?

```patch
diff --git a/.eslintrc.json b/.eslintrc.json
index 226c7a7..589a212 100644
--- a/.eslintrc.json
+++ b/.eslintrc.json
@@ -3,7 +3,7 @@
     "es6": true,
     "mocha": true
   },
-  "extends": ["airbnb-base", "plugin:prettier/recommended"],
+  "extends": ["airbnb-base", "prettier/recommended"],
   "plugins": ["import", "prettier"],
   "rules": {
     "arrow-parens": ["error", "always"],
```

**Comment by aichholzer** [comment]
Hello @toddmazierski -Thank you for that.
I did not think it was a typo as it is the [recommended configuration](https://github.com/prettier/eslint-plugin-prettier) for the plug-in.

I did, however, try your suggestion which gave me an error locally when running `npm test`.

```
Cannot find module 'eslint-config-prettier/recommended'
Referenced from: .eslintrc.json
```

Any other suggestions?

**Comment by VictorKid** [comment]
@toddmazierski  I also have the same issue,

this is my .eslintrc
```
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:prettier/recommended",
    "plugin:react/recommended"
  ],
  "rules": {
    "no-console": 0,
    "react/react-in-jsx-scope": "off"
  },
  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "jest": true
  }
}
```

this is .codeclimate.yml
```
version: "2"
plugins: 
  eslint:
    enabled: true
    channel: "eslint-4"
exclude_paths:
- "static/"
- "**/*-test.js"
- "src/config/"
```

**Comment by aichholzer** [comment]
@toddmazierski -Absolutely no worries, I appreciate you digging into this issue with me.
I made the new change you suggested and I got another error, from `ESLint` this time;
```
Unexpected newline between object and [ of property access  no-unexpected-multiline
```
The newline, however, is what `prettier` expects. Removing the plugin extension from the `.eslintrc.json` file is ignoring `prettier` in the linting process.

I also tried downgrading the version of the plugin I am using to `2.3.1` and making your suggested change, but I still got the same issue.

I guess I will just hold my horses with this until you guys upgrade the version you support.

**Comment by VictorKid** [comment]
@toddmazierski is it possible to upgrade `eslint-config-prettier` and `eslint-plugin-prettier`, to support `"extends": ["plugin:prettier/recommended"]`

**Comment by aichholzer** [comment]
@toddmazierski -I am running my tests on the Codeclimate site and locally just using `npm test` (which runs `ESLint` and `Prettier` as part of the pipeline).

- The first error is exactly the same one I get, where it seems the `prettier` plugin cannot extend what it needs; `plugin:prettier/recommended`.

- The second error, after your suggested change, is ignoring the `Prettier` config completely, which is making `ESLint` complain. My `Prettier` config:
   ```js
   "prettier/prettier": [
     "error",
     {
       "semi": true,
       "printWidth": 100,
       "singleQuote": true,
       "arrowParens": "always"
     }
    ]
    ```
    `ESLint` ignores `"arrowParens": "always"` setting when running. This error, however, should not even appear since the `.eslintrc` file has the `"arrow-parens": ["error", "always"]` rule. Interestingly strange... 🤔

- And the third error is from `ESLint` failing on something the `Prettier` format does on file save. The strange thing here is that in this case `ESLint` did respect the `"arrow-parens": ["error", "always"]` rule as defined in the `.eslintrc` file.

Looks like there is a [Ghost in the Machine](https://en.wikipedia.org/wiki/Ghost_in_the_machine) doing it's thing around here.

Locally, I am running `"eslint-plugin-prettier": "^2.6.0"` and everything plays in unison and harmony. I don't think this is a Codeclimate issue, but rather due to the plugin version. Furthermore, I don't think it's worth to put all this effort into investigating where the culprit may be.

For the time being, I will take Codeclimate out of my pipeline and remain until you guys upgrade you support for this particular plugin.

So far, thank you very much @toddmazierski 
👍

**Comment by toddmazierski** [comment]
@aichholzer, darn. Sorry that didn't help! I also suspect it's some incompatibility between these plugins.

For next steps, I'll close this particular issue, but also add upgrading (#351) to our work queue. It seems like that pull request has gone stale.

**Comment by vgrbr** [comment]
It seems that upgrading did not fix the problem with prettier. I'm still having the same issue :(

**Comment by aichholzer** [comment]
Unresolved. Outdated.

**Comment by sitch** [comment]
having a similiar problem when using:
```js
  extends: [require.resolve("@umijs/fabric/dist/eslint"), "plugin:cypress/recommended"],
```
