### ISSUE TITLE
Config for rule "import/extensions" is invalid

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-eslint#386]
## Actual Behavior
When using Code Climate's `eslint-4` channel, with the following dependencies in the package.json:

- babel-eslint@8.2.3
- eslint@4.18.2
- eslint-plugin-import@2.9.0

- [package.json.txt](https://github.com/codeclimate/codeclimate-eslint/files/1975693/package.json.txt)
- [eslintrc-import error.txt](https://github.com/codeclimate/codeclimate-eslint/files/1975694/eslintrc-import.error.txt)

With this in the .eslintrc file:

```
"import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
      }
    ],
```
---

The eslint plugin fails with the following error:

> /usr/src/app/lib/validate_config.js:18
>         throw e;
>         ^
> 
> Error: /code/.eslintrc:
> 	Configuration for rule "import/extensions" is invalid:
> 	Value ["ignorePackages",{"js":"never","jsx":"never"}] should NOT have more than 1 items.
> 	Value ["ignorePackages",{"js":"never","jsx":"never"}] should NOT have more than 1 items.
> 	Value "ignorePackages" should be equal to one of the allowed values.
> 	Value ["ignorePackages",{"js":"never","jsx":"never"}] should match some schema in anyOf.
> 

---

Possibly resolved by bumping our `eslint-plugin-import` version. (we're at [2.8.0](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json#L46))

- Related conversation on eslint-plugin-import project: https://github.com/benmosher/eslint-plugin-import/issues/979

---

## Relevant links
- reproduced here: https://github.com/efueger/tui.calendar

**Comment by efueger** [comment]
Updated `eslint-plugin-import` to v2.11.0.

- works now on my repo: https://codeclimate.com/github/efueger/tui.calendar/builds/13

Thanks @wilson! 👍 

https://github.com/codeclimate/codeclimate-eslint/commit/a7c57889fdacf7f18c5ac2eb45a07c5fa51ea4c2

**Comment by jinzhuming** [comment]
@efueger yes, is right
