### ISSUE TITLE
Update eslint-plugin-node

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-eslint#389]
# Description

Repo using `eslint-4` channel running into the following error:

```
engine eslint failed with status 1 and stderr 
/usr/src/app/lib/validate_config.js:18
        throw e;
        ^

Error: /code/.eslintrc.js:
	Configuration for rule "node/no-unsupported-features" is invalid:
	Value {"version":8.3,"ignores":[]} should be equal to one of the allowed values.
	Value {"version":8.3,"ignores":[]} should be string.
	Value 8.3 should be equal to one of the allowed values.
	Value 8.3 should be string.
	Value 8.3 should match some schema in anyOf.
	Value {"version":8.3,"ignores":[]} should match some schema in anyOf.
```

---

This is likely related to: 
- the version of **eslint-plugin-node** the engine currently supports: [5.1.1](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json#L57). 
- **eslint-plugin-node** made changes for for `no-unsupported-features` in [6.0.0 and 6.0.1](https://github.com/mysticatea/eslint-plugin-node/releases).

---

User notes the following when testing:

Works:
```
'node/no-unsupported-features': [ 
'error', 
{ 
version: 8, 
ignores: [], 
}, 
],
```
Breaks:
```
'node/no-unsupported-features': [ 
'error', 
{ 
version: 8.3, 
ignores: [], 
}, 
],
```

**Comment by filipesperandio** [comment]
Already there, closing.
