### ISSUE TITLE
Add support for CoffeeScript plugin

### ISSUE THREAD

**Issue by n-rodriguez** [codeclimate/codeclimate-eslint#390]
Hi!
Is it possible to add support of CoffeeScript plugin? (https://www.npmjs.com/package/eslint-plugin-coffeescript)
Thank you!

**Comment by larkinscott** [comment]
Hey @n-rodriguez! Adding and testing this plugin now.

**Comment by n-rodriguez** [comment]
Great :)

**Comment by larkinscott** [comment]
`eslint-plugin-coffeescript` has been added to `channel-3`. Closing this out!

**Comment by n-rodriguez** [comment]
Awesome! Thank you!
