### ISSUE TITLE
Update eslint-plugin-react

### ISSUE THREAD

**Issue by efueger** [codeclimate/codeclimate-eslint#391]
# Description

Repo using `eslint-4` channel and erroring with:

```
/usr/local/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:663
            properties = node.params[1].properties;
                                       ^

TypeError: Cannot read property 'properties' of undefined
    at markPropTypesAsUsed (/usr/local/node_modules/eslint-plugin-react/lib/rules/no-unused-prop-types.js:663:40)
```

----

I think this might be related to a versioning difference with **eslint-plugin-react**: 
- our `eslint-4` channel is compatible with [v7.7.0](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-4/package.json#L61), 
- and it looks like there was a change in support for **no-unused-prop-types** in [v7.8.0](https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.8.0).

----

Repo's config files:
- [eslint config for GH issue.txt](https://github.com/codeclimate/codeclimate-eslint/files/2037150/eslint.config.for.GH.issue.txt)
- [devDependencies for GH issue.txt](https://github.com/codeclimate/codeclimate-eslint/files/2037151/devDependencies.for.GH.issue.txt)

Contact @efueger for any additional info needed :+1:

**Comment by filipesperandio** [comment]
There is so many variations to these eslint plugins I get confused.
We have `eslint-config-react-app` might that be enough?

**Comment by filipesperandio** [comment]
Disregard my confusion. The `eslint-plugin-react` was upgraded here: https://github.com/codeclimate/codeclimate-eslint/pull/459
