### ISSUE TITLE
Enable eslint-plugin-babel for eslint v4

### ISSUE THREAD

**Issue by cbothner** [codeclimate/codeclimate-eslint#392]
eslint-plugin-babel v5.0.0 has a peer dependency on eslint v4, so it would be nice to have it reenabled in CodeClimate. I’m enabled the babel/quotes rule to support React fragment syntax, and everything just exploded with `Definition for rule 'babel/quotes' was not found`

**Comment by filipesperandio** [comment]
It's there for a while now.
