### ISSUE TITLE
Consider adding support for eslint-plugin-chai-friendly

### ISSUE THREAD

**Issue by nickytonline** [codeclimate/codeclimate-eslint#406]
# Bug Template

## Actual Behavior
Errors in the logs
```
Module not supported: eslint-plugin-ignore-erb
ESLint is running with the default parser.
Module not supported: eslint-plugin-chai-friendly
Module not supported: eslint-plugin-cypress
```

and in Code Climate I get issues reported that I need to mark as invalid because it is unable to process the rules in `eslint-plugin-chai-friendly`

## Expected Behavior
For code climate to process the eslint rules that the chai-friendly plugin provides;

## Steps to reproduce

1. Install the eslint-plugin-chai-friendly into a JavaScript project along with eslint

2. Add the following to the `.eslintrc`:
```
{
 ...
 "plugins": ["chai-friendly"],
 ...
  "rules": {
    "no-unused-expressions": 0,
    "chai-friendly/no-unused-expressions": 2
  }
}
```
3. Commit a test that uses chai in the folder or subfolder where the `.eslintrc` file resides, e.g.
```
// this
expect(foo).to.be.true;
foo.should.be.true;
```

## Relevant links
https://github.com/ihordiachenko/eslint-plugin-chai-friendly

I'd be happy to open up a PR for this.

**Comment by efueger** [comment]
Thanks @nickytonline! That should be incorporated soon.

**Comment by modosc** [comment]
hey @efueger - curious how long it'll take to get this from `master` into the `eslint-4` branch?

**Comment by modosc** [comment]
looks like this is done, thanks!
