### ISSUE TITLE
ESLint v5 support

### ISSUE THREAD

**Issue by gonstr** [codeclimate/codeclimate-eslint#411]
# Bug Template
## Actual Behavior
Lots of log errors of type:
```
Definition for rule 'node/*' was not found
```

## Expected Behavior
No log errors and proper lint results.

(codeclimate needs to support eslint 5 and plugins that require eslint version > 5.0.0)

## Steps to reproduce
In a node project...

```shell
yarn add --dev eslint eslint-plugin-node
```
.eslintrc.json
```json
{
  "extends": ["eslint:recommended", "plugin:node/recommended"]
}
```
.codeclimate.yml
```yaml
version: "2"
plugins:
  eslint:
    enabled: true
```

**Comment by travislloyd** [comment]
I'd love to see v5 support as well!

**Comment by cbarratt** [comment]
Would be great to get eslint v5 👍 It fixes an annoyance surrounding the use of React Fragments shorthand`<>`

**Comment by Hyperkid123** [comment]
+1

**Comment by mauricecruz** [comment]
I noticed there's a branch for supporting eslint-5. Is there any estimate on when this will ship as an available channel?

**Comment by krzysiek1507** [comment]
The channel is available but has some issues. #426

**Comment by modosc** [comment]
#426 is resolved now as of today - if you were running into any issues around `eslint-plugin-import` you should try again.

**Comment by filipesperandio** [comment]
Let us know if this is still a problem for some.
Will close this for now.
