### ISSUE TITLE
eslint-import-resolver-webpack broken for eslint-5 channel

### ISSUE THREAD

**Issue by modosc** [codeclimate/codeclimate-eslint#426]
# Bug Template

## Actual Behavior
every file generates this error on build:
```
Error resolving webpackConfig { Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/code/webpack/config.dev.js:1:79)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
```
and results in this new issue on every file:
```
Resolve error: Cannot find module 'webpack' NEW
```

## Expected Behavior
this doesn't happen on the eslint-4 channel. i've updated the various eslint-* modules but `eslint-import-resolver-webpack`'s version stayed the same
# Steps to reproduce
our `webpack/config.dev.js` is:
```
const webpack = require('webpack')
const merge = require('webpack-merge')
const Dotenv = require('dotenv-webpack')
const { buildCommon } = require('./common')

module.exports = merge.smart(buildCommon({ cssSourceMaps: false }), {
  devtool: 'eval',
  output: {
    filename: '[name].js',
  },
  mode: 'development',
  optimization: {
    nodeEnv: process.env.BABEL_ENV || process.env.NODE_ENV || 'development',
  },
  plugins: [
    new Dotenv(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.LoaderOptionsPlugin({
      debug: true,
    }),
  ],
})

```

## Relevant links
we are commercial customers - should i include a link to failed builds here?

**Comment by noqcks** [comment]
I can replicate this bug on my own codeclimate account with a project, but I am unable to reproduce locally using the [codeclimate-cli](https://github.com/codeclimate/codeclimate). 

It looks like it was mentioned as an issue in the eslint-4 branch as well at one point https://github.com/codeclimate/codeclimate-eslint/issues/388. 

Are you able to reproduce locally @filipesperandio ? Is there anything in the way that the engines are run on the codeclimate platform that might cause this?

**Comment by modosc** [comment]
is it possible that `webpack` was manually installed in the `eslint-4` images (or already exists on the system)? i went through the diffs, i don't see anything in them that would account for this..

**Comment by filipesperandio** [comment]
I will have to dig a bit. The results should not differ from the CLI.

**Comment by modosc** [comment]
looks like `webpack` _should_ be installed:
```
warning " > eslint-import-resolver-webpack@0.10.1" has unmet peer dependency "webpack@>=1.11.0".
```

**Comment by noqcks** [comment]
Yeah, I saw that warning as well when building the container locally @modosc, but unfortunately I still can't reproduce the issue locally. Can you?

Waiting to hear back from @filipesperandio if he's found anything.

**Comment by modosc** [comment]
> but unfortunately I still can't reproduce the issue locally. Can you?
unfortunately i don't have a local setup - our company uses the service.

**Comment by larkinscott** [comment]
👋 @modosc Would you be able to send a link to the failed build to support? https://codeclimate.com/help/new I'll grab it there and dig into this a little deeper.

**Comment by krzysiek1507** [comment]
I've reproduced this issue on my local machine using the CLI by removing `webpack` from my project. Adding `webpack` to the `package.json` fixes the problem. I've create a PR [here](https://github.com/codeclimate/codeclimate-eslint/pull/429).

**Comment by larkinscott** [comment]
@modosc 👋 I've gone ahead and updated the eslint-5 channel with @krzysiek1507's PR (thanks for that!). This should be resolved, but let me know if you're still running into any issues on your upcoming builds.

**Comment by krzysiek1507** [comment]
It works for me. I guess we can close it.

**Comment by modosc** [comment]
now it's breaking on `webpack-merge`:
```
Error resolving webpackConfig { Error: Cannot find module 'webpack-merge'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/code/webpack/config.dev.js:2:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by noqcks** [comment]
```
Error resolving webpackConfig { Error: Cannot find module 'extract-text-webpack-plugin'
```

`extract-text-webpack-plugin` is not found whether we include it in our dependencies or devDependencies.

**Comment by travislloyd** [comment]
I believe I'm having a similar issue with webpack-bundle-tracker.

`Resolve error: Cannot find module 'webpack-bundle-tracker' `

**Comment by modosc** [comment]
no need now, #432 fixes this for us
