### ISSUE TITLE
please add eslint-import-resolver-babel-module@^5.0.0-beta1 to the eslint-5 channel

### ISSUE THREAD

**Issue by modosc** [codeclimate/codeclimate-eslint#427]
there is prior art with some of the other resolvers (`webpack`,`node`). it would be great to have this one as well. happy to do a pr if that would speed things up?

**Comment by ale7714** [comment]
@modosc thank you! A PR would definitely help :). We always welcome contributions.

**Comment by modosc** [comment]
ping?

**Comment by modosc** [comment]
no need now, #432 fixes this for us
