### ISSUE TITLE
eslint-5 errors out on not supported plugins

### ISSUE THREAD

**Issue by racer01** [codeclimate/codeclimate-eslint#430]
## Actual Behavior
Errored when trying to load unsupported eslint plugin.

## Expected Behavior
Log "Module not supported" and ignore upsupported plugin.

config file: https://github.com/openHAMS/openHAMS-web2/blob/dbf0303d8e5fd03ab8bd8ae542bd16a4a8dea710/.codeclimate.yml

## Relevant links
It worked with eslint-4: https://codeclimate.com/github/openHAMS/openHAMS-web2/builds/121
but upgrading to eslint-5 broke it: https://codeclimate.com/github/openHAMS/openHAMS-web2/builds/122

**Comment by filipesperandio** [comment]
This seems to be rather a change on how ESLint itself handles the scenario.
Would you be able to achieve the expected results running `eslint` itself?

**Comment by racer01** [comment]
As far as I can tell [this patch](https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-5/lib/eslint-patch.js) logs the "module not supported" message and adds the unsupported module to the skipped modules array which I suspect is broken.

**Comment by filipesperandio** [comment]
@racer01 ESLint changed the way plugins are loaded. It is being a bit tricky to patch it up to support the same behavior. In the mean time, I've added the `eslint-comments` plugin to the engine. It is not yet released to the platform, but you should be able to try it out from the CLI.

**Comment by racer01** [comment]
Thank you for adding `eslint-comments` plugin. I closed this issue as adding said plugin fixed my problem.
