### ISSUE TITLE
Add support for 'sort-imports-es6-autofix/sort-imports-es6'

### ISSUE THREAD

**Issue by Fouppy** [codeclimate/codeclimate-eslint#438]
Hello.

Would it be possible to add support for `sort-imports-es6-autofix/sort-imports-es6`?

Codeclimate complains with this error on every file: `Definition for rule 'sort-imports-es6-autofix/sort-imports-es6' was not found`.

Thanks!

**Comment by ryanau** [comment]
@codeclimate-hermes Would appreciate if this is supported. How's the progress looking?

**Comment by ruipinge** [comment]
@Fouppy, @ryanau, Setting ESLint version to 7 did the trick for me. `.codeclimate.yml` example:
```yml
plugins: 
  eslint:
    enabled: true
    channel: eslint-7
```
