### ISSUE TITLE
Add support for 'react-hooks/rules-of-react'

### ISSUE THREAD

**Issue by guilherme6191** [codeclimate/codeclimate-eslint#439]
Hello everyone.

Would it be possible to add support for `react-hooks/rules-of-hooks`?

Just updated React to 16.8 and started using react hooks, its new feature. They suggest the usage of the `eslint-plugin-react-hooks`.
Codeclimate complains with this error on every file: `Definition for rule 'react-hooks/rules-of-hooks' was not found`.

Thanks!

**Comment by joeycozza** [comment]
I made a pr for it https://github.com/codeclimate/codeclimate-eslint/pull/441

**Comment by Sebdevar** [comment]
Can the mentioned PR be merged if ready? Our project is getting failed build because of the eslint plugin not being supported

**Comment by ale7714** [comment]
Thank you @joeycozza for opening a PR. We have merged it. Thank you for you patience all!

**Comment by aleksandrlat** [comment]
@ale7714 I see issue is closed. But when it is possible to use it? 
I just added this plugin to my project and got bunch of errors `Definition for rule 'react-hooks/rules-of-hooks' was not found `

**Comment by Pillar-Zhang** [comment]
{
  "plugins": [
    // ...
    "react-hooks"
  ],
  "rules": {
    // ...
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  }
}

**Comment by xivig** [comment]
Thanks Pillar-Zhang.
I was actually forgetting to include the  `"react-hooks"` in the plugins
