### ISSUE TITLE
Support for latest eslint and typescript support

### ISSUE THREAD

**Issue by piotrb** [codeclimate/codeclimate-eslint#442]
This mostly requires adding `@typescript-eslint/parser` as a supported module

right now you get:

```
Module not supported: @typescript-eslint/parser
ESLint is running with the /usr/src/app/lib/empty-plugin.js parser.
```

Info about this is found here:

https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by ale7714** [comment]
@piotrb thank you for the ping! engine has been updated. 

@ericrav thank you so much for you PR!
