### ISSUE TITLE
eslint 6.0 is released

### ISSUE THREAD

**Issue by modosc** [codeclimate/codeclimate-eslint#464]
https://eslint.org/blog/2019/06/eslint-v6.0.0-released

it would be great to get an eslint-6 channel.

**Comment by Loremaster** [comment]
Yes can we please get the support for eslint 6?

**Comment by esilkensen** [comment]
I was starting to look at this, found this PR as a reference for some of the breaking changes in 6.0 that will require codeclimate-eslint updates: https://github.com/eslint/eslint/pull/11546

**Comment by BenEinwechter** [comment]
Any updates on when CodeClimate will support eslint 6? Thanks!

**Comment by Loremaster** [comment]
Bump on that. Are there any plans to check it?

**Comment by efueger** [comment]
Hi @modosc - good news: the [ESLint-6 channel](https://github.com/codeclimate/codeclimate-eslint/tree/channel/eslint-6) is live!

Thanks for the nudge on this. 👌

**Comment by efueger** [comment]
To use the new version, just update your `.codeclimate.yml` with the following:

```
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"
```

PS: If you have any open, erroring branches, you'll need to first make the channel change on your default branch, and then rebase any open branches on that fresh commit.
