### ISSUE TITLE
Typescript not supported latest channel

### ISSUE THREAD

**Issue by henrikrudstrom** [codeclimate/codeclimate-eslint#468]
# Typescript not supported

## Actual Behavior
running `CODECLIMATE_DEBUG=1 codeclimate analyze -e eslint`
produces these messages:
```
Module not supported: eslint-plugin-@typescript-eslint
Module not supported: @typescript-eslint/parser
Module not supported: @typescript-eslint/eslint-plugin
```

i see it was added to the eslint-5 branch. is there any reason not to add it to the latest branch as well?

**Comment by stereodenis** [comment]
Any updates on this?

**Comment by stereodenis** [comment]
@davehenton ?

**Comment by stereodenis** [comment]
This works for me
```
plugins: 
  eslint:
    enabled: true
    channel: "eslint-6"
```

@henrikrudstrom

**Comment by davehenton** [comment]
@henrikrudstrom @stereodenis 

Sorry about the confusion with that. 

For clarity, our ESLint-5 and ESLint-6 branches **do** support the above-mentioned typescript modules. 

However, our default channel for ESLint (which runs ESLint 3.19.0) does not.

To move forward, you'll need to specify one of these newer versions of ESLint via your committed `.codeclimate.yml`, as seen in @stereodenis reply [above](https://github.com/codeclimate/codeclimate-eslint/issues/468#issuecomment-568533263).

**Comment by stereodenis** [comment]
@henrikrudstrom closing?

**Comment by henrikrudstrom** [comment]
thanks. yeah this can be closed.
