### ISSUE TITLE
Possibility to set folder for eslint

### ISSUE THREAD

**Issue by henrikrudstrom** [codeclimate/codeclimate-eslint#469]
I have a repo with a subfolder containing all the frontend javascript code and the .eslintrc. 
when i run `codeclimate analyze` I get an error that no config files are found: 
```
D, [2019-08-13T08:24:02.054136 #1] DEBUG -- : engine stderr: No rules are configured. Make sure you have added a config file with rules enabled.
```
is it possible to configure a subfolder where eslint is run, or can this feature be added?

**Comment by kkumler** [comment]
@henrikrudstrom Hi, from looking at [the Code Climate docs](https://docs.codeclimate.com/docs/eslint#section-adding-a-eslintrc-js), you should be able to specify in `.codeclimate.yml` the path to the eslint config. You may be able to limit its execution with that config, or from the Code Climate exclusion patterns.

**Comment by efueger** [comment]
Thanks @kkumler ! Right on. @henrikrudstrom , let me know if you have any trouble with that. Happy to help further.
