### ISSUE TITLE
Support for eslint-config-airbnb v18.x

### ISSUE THREAD

**Issue by husseinbob** [codeclimate/codeclimate-eslint#475]
What do we do if our version of `eslint-config-airbnb`, is different (18.x, while you seem to be supporting 17.1.1)? Right now CC is complaining about violations of rules we aren't subscribed to because of the differences between versions (eg update to `arrow-parens`).

Anything besides manually going through and updating all the rules to match?

**Comment by borisrorsvort** [comment]
I’m on airbnb 17 and ESLint 5 and also have the warning that I should not apply arrow-parens while airbnb should allow it.

@husseinbob did you solve it?

**Comment by efueger** [comment]
Hi @husseinbob and @borisrorsvort - apologies for dropping this!
- I'll close it for now, but let me know if we should investigate further.
