### ISSUE TITLE
EngineFailure with status 137 and no stderr 

### ISSUE THREAD

**Issue by antoineverger** [codeclimate/codeclimate-eslint#6]
Hi guys, 

I got this error using the CLI :
```
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 137 and stderr ""
```
It does not tell me that much but here is my .eslintrc : 

```
{
  "globals": {
    "rewire" : true,
    "rewireModule" : true
  },
  "parser": "esprima-fb",
  "ecmaFeatures": {
    "jsx": true
  },
  "env": {
    "jasmine": true,
    "browser": true
  }
}
```
In this specific project, I have a second issue. I removed it from the config file above but I also use the eslint react plugin (https://github.com/yannickcr/eslint-plugin-react) and I get this error in that case :

```
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr "module.js:338\n    throw err;\n          ^\nError: Cannot find module 'eslint-plugin-react'
```
Hope that helps and if not let me know and I´ll give you more input.

**Comment by mansona** [comment]
I've just hit the same issue, let me know if there is any diagnostics I can do to help out with this

**Comment by mansona** [comment]
Could it simply just be a issue with running out of memory? https://github.com/codeclimate/codeclimate/issues/23

**Comment by jdelStrother** [comment]
I doubled the amount of memory available to 4GB.  I no longer get this error - it's now replaced with "(CC::Analyzer::Engine::EngineTimeout) engine eslint ran past 900 seconds and was killed" :/

**Comment by GordonDiggs** [comment]
This issue might have been because of the way we were excluding files. I've just pushed a version that changes that. Will you try running `codeclimate engines:install` before your next analysis to see if you still get these errors?

**Comment by jdelStrother** [comment]
Works for me

**Comment by GordonDiggs** [comment]
Closing as this seems to be resolved. Feel free to reopen if you are still having trouble!

**Comment by robrohan** [comment]
I get this error too.  I am running the default brew command, and I have tried the `codeclimate engines:install` command as well.

    Starting analysis
    Running csslint: Done!
    Running duplication: Done!
    Running eslint: Done!
    Running fixme: Done!
    Running phpmd: Done!
    error: (CC::Analyzer::Engine::EngineTimeout) engine phpmd ran for 900 seconds and was killed

Docker version 1.10.3, build 20f81dd
Mac 10.11.4  3.1GHz, 16GB

Let me know if I can provide anything else to help.  That's not a lot to go on.

**Comment by Van-Tien** [comment]
Anyone can help on this ? I got the same issue on my build system

**Comment by timbuckley** [comment]
I'm also getting this error
