### ISSUE TITLE
Support older versions of eslint & plugins moving forward?

### ISSUE THREAD

**Issue by jakemhiller** [codeclimate/codeclimate-eslint#78]
The recent updates to `eslint-config-airbnb` and `eslint-plugin-react` caused a lot of issues as our team all of the sudden had branches failing that were previously passing.

I'm wondering if there is a way for you to support using older versions of eslint and the supported parsers/plugins moving forward.

It seems like you support older versions of rubocop through the `codeclimate.yml` config, just wondering if there were plans to extend this to eslint eventually.

#76 is related, as this will break compatibility with a lot of rules (afaik).

**Comment by dblandin** [comment]
Hi @jakemhiller,

We recently introduced the concept of channels to Code Climate engines which will allow us to support multiple versions of ESLint and supported plugins moving forward.

The default channel is `stable` which currently targets ESLint v1. The other currently available channel is `eslint-2` which you can opt-in to by updating your `.codeclimate.yml` configuration file:

```yaml
engines:
  eslint:
    enabled: true
    channel: eslint-2
```

Looking forward a bit, we'll eventually update the `stable` channel to target ESLint v2, but will give users the option to pin to ESLint v1, likely with an `eslint-1` channel.

Hope that helps! Let me know if you have any further questions.

**Comment by jakemhiller** [comment]
Great news, thanks!
