### ISSUE TITLE
Add support for new ESLint configuration file formats

### ISSUE THREAD

**Issue by ntwb** [codeclimate/codeclimate-eslint#81]
via http://eslint.org/docs/user-guide/configuring#configuration-file-formats

ESLint supports configuration files in several formats:

  * **JavaScript** - use `.eslintrc.js` and export an object containing your configuration.
  * **YAML** - use `.eslintrc.yaml` or `.eslintrc.yml` to define the configuration structure.
  * **JSON** - use `.eslintrc.json` to define the configuration structure. ESLint’s JSON files also allow JavaScript-style comments.
  * **Deprecated** - use `.eslintrc`, which can be either JSON or YAML.
  * **package.json** - create an `eslintConfig` property in your `package.json` file and define your configuration there.

If there are multiple configuration files in the same directory, ESLint will only use one. The priority order is:
1. `.eslintrc.js`
2. `.eslintrc.yaml`
3. `.eslintrc.yml`
4. `.eslintrc.json`
5. `.eslintrc`
6. `package.json`

**Comment by GordonDiggs** [comment]
@ntwb This precedence should already be supported. Are you seeing something different?

**Comment by ntwb** [comment]
No, I haven't actually tried any of these, this is based on the [docs](https://docs.codeclimate.com/docs/eslint) where `.eslintrc` is pretty much the only term referenced, kind of explicitly in my opinion :smirk: 

If this is indeed the case maybe change the issue to: "Update the ESLint docs support of the new ESLint configuration file formats" or similar.


P.s. I'd emailed support last night for various ESLint issues and was pointed to this repo, so I'll create my issues as issue here :smile:

**Comment by ntwb** [comment]
Closing this, docs have been updated by the looks of things, thanks 👍
