### ISSUE TITLE
error: (CC::Analyzer::Engine::EngineFailure) engine eslint:eslint-2 failed with status 139 and stderr

### ISSUE THREAD

**Issue by troym9731** [codeclimate/codeclimate-eslint#99]
I get this error after running the following:
```
codeclimate analyze
Starting analysis
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint:eslint-2 failed with status 139 and stderr
```

I noticed some similar issues brought up in the past about a year ago. A difference with this error is that I can get it to run successfully when I take away `channel: "eslint-2` out of the `.codeclimate.yml`. However, then some ESLint rules do not work. 

This analysis is being run on a decently large codebase. Any ideas on how I can proceed?

**Comment by dblandin** [comment]
Hey @troym9731,

Thanks for the issue! Sorry you having trouble with the ESLint 2 channel.

I'd recommend running the CLI in debug mode to see if any useful output is produced just prior to the error:

```
$ CODECLIMATE_DEBUG=1 codeclimate analyze
```

I've found some GH issues related to status 139 (segfault), particularly [this issue](https://github.com/nodejs/node/issues/2763), in which some commenters recommend a clean install of your npm dependencies with `npm rebuild` or `rm -rf ./node_modules && npm install`.

Let me know if any of those steps solves the problem. You might also try running [ESLint 2](https://github.com/eslint/eslint) locally on you machine to determine whether this is a problem with the Code Climate engine or ESLint 2.

**Comment by troym9731** [comment]
Unfortunately, `rm -rf node_modules && npm i` did not fix the issue. Also, ESLint 2 succeeds in running locally on its own.

The debug mode just added the following trace, otherwise the error was the exact same as above. It doesn't mean anything to me haha, but perhaps it gives you some insight?

If not, and I'm the only one having this issue, then I'll continue to poke around over the next few days to see if I find anything new. Regardless, thank you for your help! 

```
[DEBUG] backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:17:in `finished'
	/usr/src/app/lib/cc/analyzer/container.rb:74:in `run'
	/usr/src/app/lib/cc/analyzer/engine.rb:52:in `run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:60:in `block in run_engine'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:74:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:55:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:18:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:54:in `engine_running'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:59:in `run_engine'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `block in run'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `each'
	/usr/src/app/lib/cc/analyzer/engines_runner.rb:23:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:20:in `block in run'
	/usr/src/app/lib/cc/cli/analyze.rb:18:in `chdir'
	/usr/src/app/lib/cc/cli/analyze.rb:18:in `run'
	/usr/src/app/lib/cc/cli/command.rb:24:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:22:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:8:in `run'
	/usr/src/app/bin/codeclimate:6:in `<main>'
```

**Comment by aaronjudd** [comment]
I am also seeing this error (exact same output in debug mode), and it occurs when running local tests using the CLI as well the codeclimate online analysis.

**Comment by pbrisbin** [comment]
I would recommend running with a formatter that streams issues as their found (e.g. `-f json`). When trouble shooting another case of eslint-2 segfaulting, I was able to see a huge amount of issues being reported for a minified javascript file just before the segfault. Excluding the minified file was the solution there.

**Comment by pbrisbin** [comment]
We believe we've addressed the source of segfaults in the eslint-2 engine. I'm going to go ahead and close this, but feel free to re-open with more details if you update your engine and still encounter the issue.
